### ISSUE TITLE
A reporter added to the end of a CompositeReporter doesn't appear to be getting called

### ISSUE THREAD

**Issue by hakanai** [minitest/minitest#943] opened 2023-02-08 05:54 UTC
Originally from https://github.com/ci-reporter/ci_reporter_minitest/issues/7 -

On investigating this issue, I found that the `CompositeReporter` did contain `CI::Reporter::Runner` as one of the reporters, yet its report methods were somehow never being called.

The issue might be the way that `CompositeReporter` is calling its child reporters:

https://github.com/minitest/minitest/blob/master/lib/minitest.rb#L881-L885

If any reporter gets an error, this error will propagate and cause subsequent reporters not to get run. Now, why would a reporter give an error? Because whatever is happening, we don't seem to receive any useful stack trace we can investigate, so it must be getting caught at some other level and then dropped without reporting it.

Perhaps an error from a reporter should cause a hard abort, so that no further tests run at all and you just get the error from the reporter on the console... that way there would be some kind of lead to figure out who is throwing it.

Another option might be to log it, but if I had `CI:Reporter::Runner` throw an error, that would mean we'd be missing test reports at random, which I'd call a critical failure.

So what I have so far is:
* The way `CompositeReporter` is implemented would definitely cause the later reporters to be skipped
* While I was trying to diagnose this, I found that `Minitest::SummaryReporter.to_s` threw an "undefined method `string` for nil" exception when called, which may be related?

**Comment by zenspider** [comment] 2023-02-08 10:12
There's no workable information in this report... I'm not sure what you want me to do with this.

Run your test with `ruby -d` and you'll see EVERY exception raised, whether it is rescued or not. If it is a rails app, it'll be a LOT of noise to sift through, but somewhere in there will be your culprit.

**Comment by hakanai** [comment] 2023-02-08 10:45
If you want the short summary, this method is broken, because if an exception happens from the first reporter it calls, the rest of them will not be called:

https://github.com/minitest/minitest/blob/master/lib/minitest.rb#L881-L885

Also this one:

https://github.com/minitest/minitest/blob/master/lib/minitest.rb#L887-L889

Also this one:

https://github.com/minitest/minitest/blob/master/lib/minitest.rb#L874-L879

And also this one:

https://github.com/minitest/minitest/blob/master/lib/minitest.rb#L870-L872

But yes, I am going to go digging for an exception so that I can hopefully also figure out _what_ is causing it. That may result in a _second_ ticket, but _this_ ticket is about a reporter further down the list not being called if an earlier one bombs out.

**Comment by hakanai** [comment] 2023-02-08 11:04
I thought I'd try to quickly check this out right now, but it turns out setting -d doesn't help me because either rake or minitest is spawning a new process to actually run the test. I have to figure out where that happens and how to add the option for _that_ ruby. So this will be tomorrow.

I also dug up a way to log all method invocations, which will make the log much bigger but might make it easier to get to the right place in the log, because I know that `record` _must_ be getting called, otherwise I wouldn't be seeing the green dots - but I also know that `record` isn't being called on the third reporter, otherwise it would have at least created the report file.

**Comment by hakanai** [comment] 2023-02-08 21:45
OK, I was close, but it wasn't `record` - it was `report`. Some other plugin was throwing an exception from `report`, so it didn't run the later ones.

Now I'm trying to figure out why an exception thrown from there didn't even print a stack trace or result in a failure.

**Comment by hakanai** [comment] 2023-02-08 21:52
As far as I can tell, the call to `run` is this one:

https://github.com/minitest/minitest/blob/master/lib/minitest.rb#L83

**Comment by zenspider** [comment] 2023-02-09 08:25
Bad reporters raising exceptions during `report` raise, report their stack trace, and have non-zero exit code just fine:

```
9992 % ruby -Ilib -rminitest/autorun -e 0 -- --bad ; echo $?
Run options: --bad --seed 29269

# Running:



Finished in 0.000280s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
/Users/ryan/Work/p4/zss/src/minitest/dev/lib/minitest/bad_plugin.rb:18:in `report': undefined method `exists?' for File:Class (NoMethodError)

      p File.exists? "/tmp/woot"
            ^^^^^^^^
Did you mean?  exist?
	from /Users/ryan/Work/p4/zss/src/minitest/dev/lib/minitest.rb:888:in `each'
	from /Users/ryan/Work/p4/zss/src/minitest/dev/lib/minitest.rb:888:in `report'
	from /Users/ryan/Work/p4/zss/src/minitest/dev/lib/minitest.rb:164:in `run'
	from /Users/ryan/Work/p4/zss/src/minitest/dev/lib/minitest.rb:83:in `block in autorun'
1
```

**Comment by hakanai** [comment] 2023-02-09 22:44
I'm running from rake, so I wonder if rake is the culprit.

**Comment by zenspider** [comment] 2023-02-21 01:49
It's not rake. 

If you want run rake with `-t` to see what it is running and then run it yourself directly. It could be as simple as `ruby -Ilib test/file.rb`

**Comment by hakanai** [comment] 2023-02-26 09:03
`rake -t` isn't even telling me what it's running. Even though in the help it shows up as an option.

So I try running `ruby -Ilib test/models/user_test.rb` - it runs. Similar deal, tests pass, exit code 0, no report files.

**Comment by zenspider** [comment] 2023-03-04 22:27
There's not enough here for me to work with. The problem is in your plugins. Stop using ci-reporter and the problem will go away. (I seriously doubt you'll ever get an update out of it to fix the problem).

Closing

**Closed by zenspider** 2023-03-04 22:27 UTC
