### ISSUE TITLE
RuntimeError: instance variable added to NameError instance

### ISSUE THREAD

**Issue by artemave** [minitest/minitest#895] opened 2022-01-25 14:54 UTC
After this change was merged https://github.com/seattlerb/minitest/commit/ad135e9def3d9dd9264e0cfa82c85f8f86f6ade1 _some_ of our test errors are being masked by the following one:

```
Error:
TasksControllerTest#around_all:
RuntimeError: instance variable added to NameError instance
```

For example, we'd get that when trying to use a non-existent method.

With `Marshal.dump` commented out, the actual test error is shown as expected. E.g.:

```
NameError: undefined local variable or method `bbbbbb' for #<TasksControllerTest:0x00007fe000496618>
```

I couldn't figure out how to reproduce the error, but the fact remains that in _some cases_ `Marshal.dump` raises with something other than `TypeError`.

Our ruby version is 2.7.5p203.

**Comment by gstokkink** [comment] 2022-02-17 10:42
We have the same thing occurring here, with Minitest 5.15.0 and Ruby 2.7.5p203.

**Comment by sokkalf** [comment] 2022-04-28 13:21
We're having the same problem.

We use mechanize in a test, and it occasionally gets a Net::ReadTimeout. In our case, an IOError gets passed to `Marshal.dump` and it crashes. This also stops execution of all following tests, so this is a big problem for us. Only solution we found was to downgrade to 5.14.

```
# Running:                                                                                
                                                                                                                                                                                     
Traceback (most recent call last):                                                        
        36: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:73:in `block in autorun'                                                          
        35: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:146:in `run'
        34: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `__run'                                                                    
        33: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `map'
        32: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `block in __run'                                                           
        31: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/test_unit/line_filtering.rb:10:in `run'                               
        30: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:335:in `run'                                                                      
        29: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:363:in `with_info_handler'
        28: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
        27: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `block in run'
        26: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `each'
        25: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:337:in `block (2 levels) in run'
        24: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:350:in `run_one_method'                                                           
        23: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:1042:in `run_one_method'
        22: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:93:in `run'                                                                  
        21: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:221:in `with_info_handler'
        20: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
        19: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:94:in `block in run'
        18: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:281:in `time_it'
        17: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:95:in `block (2 levels) in run'
        16: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:195:in `capture_exceptions'
        15: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:98:in `block (3 levels) in run'
        14: from test/integration/integration_test.rb:38:in `test_using_mechanize'
        13: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/mechanize-2.7.7/lib/mechanize.rb:464:in `get'
        12: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:280:in `fetch'
        11: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:885:in `request'
        10: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:606:in `connection_for'
         9: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:891:in `block in request'
         8: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/http.rb:1492:in `request'
         7: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
         6: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
         5: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
         4: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
         3: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
         2: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'                                                                                    
         1: from /usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/usr/local/rbenv/versions/2.7.5/lib/ruby/2.7.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)                                    
        24: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:73:in `block in autorun'                                                          
        23: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:146:in `run'
        22: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `__run'                                                                    
        21: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `map'                                                                      
        20: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:169:in `block in __run'
        19: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/test_unit/line_filtering.rb:10:in `run'
        18: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:335:in `run'
        17: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:363:in `with_info_handler'                                                        
        16: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
        15: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `block in run'
        14: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:336:in `each'                                                                     
        13: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:337:in `block (2 levels) in run'                                                  
        12: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:350:in `run_one_method'                                                           
        11: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:1042:in `run_one_method'
        10: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:93:in `run'
         9: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:221:in `with_info_handler'
         8: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
         7: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:94:in `block in run'
         6: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest.rb:281:in `time_it'
         5: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:95:in `block (2 levels) in run'
         4: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:194:in `capture_exceptions'
         3: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:201:in `rescue in capture_exceptions'
         2: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:205:in `sanitize_exception'
         1: from /home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:205:in `dump'
/home/vagrant/my_project/vendor/bundle/ruby/2.7.0/gems/minitest-5.15.0/lib/minitest/test.rb:205:in `internal_encoding': closed stream (IOError)
```

**Comment by zenspider** [comment] 2022-06-11 22:19
That `Marshal.dump` is there for a reason... 

I believe I have addressed this, but since there is no reproduction here, I can only guess. Closing. Please reopen a new ticket with a reproduction after the next release if there are edge cases I didn't cover.

**Closed by zenspider** 2022-06-11 22:19 UTC
